name: Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches:
    - main

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.0'
        bundler-cache: true
    - name: Run tests
      run: bundle exec ruby tests/test.rb